---

# (c) Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: include default variables
  include_vars: "../vars/main.yml"

- name: include release specific variables
  include_vars: "{{ lookup('first_found', _params) }}"
  vars:
    _params:
      files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - "../vars"
  ignore_errors: true

- name: include release specific tasks
  include_tasks: "{{ lookup('first_found', _params) }}"
  vars:
    _params:
      files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - "."
  ignore_errors: true

- name: prepare directories
  file:
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0755') }}"
    state: "{{ item.state | default('directory') }}"
  loop:
    - { dest: "/etc/ceph" }
    - { dest: "/lib/systemd/system" }
    - { dest: "/lib/systemd/system/ceph-radosgw.target.d" }
    - { dest: "/var/lib/ceph/radosgw/ceph-rgw.{{ inventory_hostname }}", owner: "ceph", group: "ceph" }

- name: touch files
  copy:
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
    content: ""
    force: false
  loop:
    - { dest: "/etc/ceph/ceph.conf", owner: "ceph", group: "ceph" }

- name: tweak settings in ini files
  ini_file:
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    state: "{{ item.state }}"
    path: "/etc/ceph/ceph.conf"
    mode: "0644"
  loop: "{{ ceph_rgw_config }}"
  notify:
    - ceph_rgw | systemctl restart ceph-radosgw.target

- name: prepare files
  file:
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
    state: "{{ item.state | default('file') }}"
  loop:
    - { dest: "/etc/ceph/ceph.conf", owner: "ceph", group: "ceph" }
  notify:
    - ceph_rgw | systemctl restart ceph-radosgw.target

- name: create manager keyring
  shell: |
    set -euo pipefail
    ceph \
      auth get-or-create client.rgw.{{ inventory_hostname }} \
      mon 'allow rw' \
      osd 'allow rwx' \
      --out-file /var/lib/ceph/radosgw/ceph-rgw.{{ inventory_hostname }}/keyring
    chown ceph:ceph /var/lib/ceph/radosgw/ceph-rgw.{{ inventory_hostname }}/keyring
    chmod 0600 /var/lib/ceph/radosgw/ceph-rgw.{{ inventory_hostname }}/keyring
  args:
    executable: "/bin/bash"
    creates: "/var/lib/ceph/radosgw/ceph-rgw.{{ inventory_hostname }}/keyring"
  register: result
  changed_when: result is not succeeded
  notify:
    - ceph_rgw | systemctl restart ceph-radosgw.target

- name: copy templates
  template:
    dest: "{{ item.dest }}"
    src: "{{ item.src | default('./templates' + item.dest + '.j2') }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
  loop:
    - { dest: "/lib/systemd/system/ceph-radosgw.target" }
    - { dest: "/lib/systemd/system/ceph-radosgw@.service" }
  notify:
    - ceph_rgw | systemctl daemon-reload
    - ceph_rgw | systemctl restart ceph-radosgw.target

- name: prepare files
  file:
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
    state: "{{ item.state | default('file') }}"
  loop:
    - { dest: "/lib/systemd/system/ceph-radosgw.target" }
    - { dest: "/lib/systemd/system/ceph-radosgw@.service" }
    - { dest: "/var/lib/ceph/radosgw/ceph-rgw.{{ inventory_hostname }}/keyring", owner: "ceph", group: "ceph", mode: "0600" }
  notify:
    - ceph_rgw | systemctl daemon-reload
    - ceph_rgw | systemctl restart ceph-radosgw.target

- name: flush handlers
  meta: flush_handlers

- name: "systemctl start ceph-radosgw@rgw.{{ inventory_hostname }}.service"
  shell: |
    set -euo pipefail
    systemctl enable ceph-radosgw@rgw.{{ inventory_hostname }}.service
    systemctl start ceph-radosgw@rgw.{{ inventory_hostname }}.service
  args:
    executable: "/bin/bash"
  changed_when: false
  ignore_errors: true

- name: systemctl start ceph-radosgw.target
  service:
    name: "ceph-radosgw.target"
    state: "started"
    enabled: true
  changed_when: false
  ignore_errors: true
